language: ruby
before_script:
  - gem install netrc --version=0.7.7
  - gem install rest_client addressable
  - touch ~/.netrc
  - chmod 0600 ~/.netrc
env:
  global:
    - "COLUMNS=80"
    - "SOLVEBIO_API_KEY=0cedb161d845e6a58ec6781478b8314c536e632f"
script: rake
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.1
  - 2.1.2

notifications:
slack:
    secure: WvTImIlFKtCSTrcpk11RB467ybQBmZatk1k9CEEb5qkRRX0IUhmmNzV4xKIJR40Hf1u84uW6j5AeD/OChHycU+1C/OmMgyFAIYMAkE8db+dGtpdlQO5a5Jj9xzK8nfUKrw6Y3JzDTn+mQkeFyRP6D8fj3WPWOV5G9EOTY62sLiQ=
