language: ruby
sudo: false
before_script:
- gem install netrc --version=0.7.7
- gem install rest_client addressable webmock
- touch ~/.netrc
- chmod 0600 ~/.netrc
env:
  global:
  - COLUMNS=80
script: rake
rvm:
- 1.9.3
- 2.0.0
- 2.1.1
- 2.1.2
notifications:
  slack:
    secure: aIpZOAZwIk/3ZToZqAPEdM4yKyD6UuDmR+KyH2eL+24mTxU+Jp8hum02LlRsdeOXweup9Ov/h7SuDQXfEt506oLmkhfDwk+v2j2RkHmFco4l4M+rI1QAtJw1xhzrscwgnJqkW8n81U5Se84KzU+x7N6EvDcki8G1KlbuU2A9f74=
