language: ruby
before_script:
  - gem install netrc
  - touch ~/.netrc
  - chmod 0600 ~/.netrc
script: rake
env:
  - "SOLVEBIO_API_KEY=0cedb161d845e6a58ec6781478b8314c536e632f"
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.1
  - 2.1.2
