language: ruby
before_script:
  - gem install netrc --version=0.7.7
  - gem install rest_client addressable
  - touch ~/.netrc
  - chmod 0600 ~/.netrc
env:
  - "COLUMNS=80"
script: rake
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.1
  - 2.1.2
